copy ..\bin\FSharpShared.dll . /y
copy ..\bin\FSharpShared.pdb . /y
copy ..\bin\PlanetWarsServer.exe . /y
copy ..\bin\PlanetWarsServer.exe.config . /y
copy ..\bin\PlanetWarsServer.pdb . /y
copy ..\bin\PlanetWarsShared.dll . /y
copy ..\bin\PlanetWarsShared.dll.config . /y
copy ..\bin\PlanetWarsShared.pdb . /y
copy ..\bin\SharedInterfaces.dll . /y
copy ..\bin\SharedInterfaces.pdb . /y