<div id="footer" class="border">
	
	<span class="abs left cdark">Site by maackey</span> <div class="center"><a>Credits</a> | <a>Contact</a> | <a>Terms of Use</a> | <a>Copyright</a></div>
	
	<!-- Legal
	<p>CA uses artwork (models, textures) donated from various sources under open-source licenses, particularly the <a href="">GNU GPL</a> and the various <a href="">Creative Commons</a> licenses. These may be copied and edited and used in derivative works according to the terms of their respective licenses. CA also uses Public Domain (PD) material.</p>
	<p>The main project and all Lua code contained within is released under the terms of the GNU General Public License.</p>
	-->
</div><!close footer>
