<div id="menu" class="border">
<table>
	<tr>
	<td><a href="index.php">Home</a></td>
	<!link to a thank you page maybe?>
	<!--td><ul class="menu">
	<li><a onclick="javascript:download();" class="menu-border button" style="color: white">Download</a>
		<ul class="menu-border">
			<li><a target="_new" href="missions.mvc">Missions</a>
			<li><a target="_new" href="maps.mvc">Maps</a>
		</ul>
	</ul> </td-->
	<td><ul class="menu">
	<li><a href="download.php">Download</a>
		<ul>
			<li><a href="download.php">Windows</a></li>
			<li><a href="download.php">Linux<span>This will now be the only game you ever play</span></a></li>
			<li><a href="download.php">Mac</a></li>
			<li><a href="http://code.google.com/p/zero-k/source/checkout">Sources<span>You awesome, intelligent man-beast, you...</span></a></li>
		</ul>
	</li>
	</ul> </td> 
	<td><ul class="menu">
	<li><a href="screen.php">Media</a>
		<ul class="menu-border">
			<li><a href="screen.php">Screenshots<span>Take a picture, it lasts longer</span></a></li>
			<li><a href="video.php">Video<span>A video says a thousand pictures</span></a></li>
			<li><a target="_new" href="http://trac.caspring.org/wiki/ConceptArt">Concept Art~</a></li>
			<li><a href="screen.php">Wallpapers<span>When busty, sexy, hawt women just aren't good enough</span></a></li>
		</ul>
	</li>
	</ul> </td>
	
	<td><ul class="menu">
	<li><a href="guide-newbie.php">Guide</a>
		<ul class="menu-border">
			<li><a href="/Wiki.mvc">Introduction<span>Don't know where to begin? Click here.</span></a></li>
			<li><a href="guide-units.php">Units*</a></li>
			<li><a target="_new" href="http://springinfo.info/guides/?p=195">Economy*</a></li>
			<li><a href="guide-terraform.php">Terraforming<span>Let's go play in the dirt!</span></a></li>
		</ul>
	</li>
	</ul> </td> 
	
	<td><a href="/Wiki.mvc">Wiki</a></td>

	<td><a target="_new" href="http://springrts.com/phpbb/viewforum.php?f=42">Forums~</a></td> 
	
	<td><ul class="menu">
	<li><a target="_new" href="http://code.google.com/p/zero-k/">Contribute~</a>
		<ul class="menu-border">
			<li><a target="_new" href="http://planet-wars.eu/ModelBase">Artwork<span>We will take pretty much anything at the moment D:</span></a></li>
			<li><a target="_new" href="http://code.google.com/p/zero-k/issues/entry">Bugs?<span>Let us know so we can <b>squash them!</b></span></a></li>
			<li><a target="_new" href="http://code.google.com/p/zero-k/source/browse/trunk#trunk/mods/zk">Code</a></li>
		</ul>
	</li>
	</ul> </td> 
	
	<td width="100%">
	<!-- search bar, and possibly a login/register input as well -->
	<form action="http://www.google.com/search">
		<table>
		<tr>
			<!--login will replace the searchbar when clicked (ala moddb)
			<td><a href="">Login</a></td>
			<input type="text" size="9" name="nick" id="nick" value="Nickname" onClick="clearinput('nick');" />
			<input type="text" size="9" name="pass" id="pass" value="Password" onClick="clearinput('pass');" />
			-->
			<td width="100%" align="right"><input type="text" name="q" id="search" onclick="clearinput('search');" value="Search" class="" /></td>
			<!--plain input
			<td width="100%" align="right"><input type="text" name="q" id="search" onclick="clearinput('search');" value="Search" class="" /></td>
			<td><input type="submit" value="Q" /></td>
			-->
		</tr>
		</table>
	</form>
	</td>
</tr>
</table>
</div><!close navigation>
