<div class="wiki-toc border">
	<ul>
		<li><a href="#NewbieGuide">Newbie Guide</a>
		<ul>
			<li><a href="#Chapter1:BasicGameplayCommandsandControls">Chapter 1: Basic Gameplay, Commands and Controls</a>
			<li><a href="#Chapter2:UnitRoles">Chapter 2: Unit Roles</a>
			<ul>
				<li><a href="#PrimaryClasses">Primary Classes</a>
				<li><a href="#Secondaryclasses">Secondary classes</a>
			</ul>
			<li><a href="#Chapter3:BasicFieldOperations">Chapter 3: Basic Field Operations</a>
			<li><a href="#MoreReading">More Reading</a>
		</ul>
	</ul>
</div>

<div id="guide" class="border">
<div id="ch1" class="">
	<h1 id="NewbieGuide">Newbie Guide</h1> 
	<p>New to Complete Annihilation? New to Spring? New to RTS games, even? This guide will show you the ropes.</p> 
	<h2 id="Chapter1:BasicGameplayCommandsandControls">Chapter 1: Basic Gameplay, Commands and Controls</h2> 
	<p>This chapter tries to teach you everything you need to know to play the game. </p> 
	<p>As soon as the game finished loading you usually get to choose a location for your command unit. This is called a <i>start</i> or <i>spawn</i> position. You usually want to choose a spot which allows you to place metal extractors right at the start of the game, as these are your main means of resource gathering. Additional advantages like expandability, access to nearby important map-features, etc. can play an important role in deciding for a spawn point.</p>
	
	<div id="1" class="">
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_1.png"><img class="border left" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_1.png" /></a> 
		<p> 1) First try to zoom out to get an overview of the map. Use your mouse wheel, or PageUp to zoom out. You can also press TAB to instantly get an overview over the whole map.</p> 
		<p> The rectangle marked green is the area in which your team's players can choose their spawning position. The red one is reserved for the opposing team.</p> 
		<hr />
	</div><!close 1>
	
	<div id="2" class="">
		<p>	2) Now press F4 to access the <i>metal map</i>. It highlights metal deposits using green and teal color hues. These <i>metal spots</i> are of high strategic value. Usually three such spots can be found close together - spawning right next to them is important to be able to construct <i>metal extractors (MEX)</i> right after the game starts for an early and steady income of metal.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_2.png"><img class="border" width="300" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_2.png" /></a> 
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_3.png"><img class="border" width="300" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_3.png" /></a>
		<p>	Comparison: metal map active on the second image.</p>
		<p>	Click the left mouse button to place a new spawn point. Press F4 to toggle between the default and the metal map view.</p>
	</div><!close 2>

	<div id="3" class=""> 
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_4.png"><img class="border left" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_4.png" /></a>
		<p>	3) Now is usually the right time to greet your teammates and forge plans with them. After doing so you want to click on the ready button so the game can finally start.</p><p>	After a countdown of three seconds your commander will appear at your spawn point.</p>
		<hr />
	</div><!close 3>

	<div id="4" class="">
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_6.png"><img class="border left" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_6.png" /></a>
		<p>	4) You can now select the commander by either left clicking it or drawing a rectangle around it by holding down the left mouse button. Your command unit can also be selected with the keyboard shortcut <strong>CTRL+C</strong>.</p>
		<p>	The first thing you usually want to do is set up a basic economy to ensure steady income and a factory for unit production.</p>
		<hr />
	</div><!close 4>

	<div id="5" class="">
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_7.png"><img class="border left" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_7.png" /></a>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_8.png"><img class="border right" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_8.png" /></a>
		<p>	5) With your commander selected, <strong>hold down the right mouse button</strong> or press B to access the build menu.</p>
		<p>	The menu displays various important buildings and building categories. (example: the metal extractor (MEX) at the top is used to represent ECOnomic buildings)</p>
		<p>	You can move around the mouse, or use the keys q, w, (e), a, d, y/z, x, c, to quickly navigate through it and access further building options.</p>
		<p>	Hovering over the metal extractor or pressing W gives you access to the economic category, displaying further buildings. To the right you can see expensive energy sources, with the upper right one being the most expensive. For now however, we will stick to the metal extractor. Release the mouse button while hovering over the extractor or press W to select it.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_9.png"><img class="border left" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_9.png" /></a>
		<p>	Now place the building on top of one of the metal spots, right next to where your commander should have spawned, by moving your mouse over it and clicking the left mouse button. Make sure the blue-green area is inside the metal extractors red circle when doing so, as this shows the range of your building.</p>
		<p>	Note: Players refer to metal extractors as mex or mexes most of the time.</p>
		<hr />
	</div><!close 5>

	<div id="6" class="">
		<p>	6) You can build any other buildings the same way as you built your metal extractor. Simply move your mouse over them before releasing it, or press the appropriate key.</p>
		<p>	Holding down the SHIFT key while placing a building allows you to queue up multiple buildings to your command units build orders.</p>
		<p>	Important building categories are:</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_10.png"><img class="border left" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_10.png" /></a>
		<p>	<strong>Factories</strong> from top left to bottom right:</p>
		<ul>
			<li>Walkers (W)
			<li>Hovers (E)
			<li>Kbots (A)
			<li>Tanks (C)
			<li>Light Vehicles (X)
		</ul>
		<hr />
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_11.png"><img class="border left" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_11.png" /></a>
		<p>	<strong>"Light" defenses</strong> </p>
		<ul>
			<li>light laser tower (X) aka. llt
			<li>heavy laser tower (Q) aka. hlt 
			<li>pop up aa turret (A)
			<li>pop up defense turret (Z)
			<li>light missile tower (E) aka. lmt
			<li>antiswarm turret (D)
			<li>specialty turret (C) arm: paralyze, core: push/pull
		</ul>
		<hr />
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_12.png"><img class="border left" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_12.png" /></a>
		<p>	<strong>AUX</strong> - radars and other supportive stuff</p>
		<ul>
			<li>radar tower (D)
			<li>long range radar (Q)
			<li>nanotower (W)
			<li>sonar (E)
			<li>metal storage (C)
			<li>energy storage (X)
			<li>specialty tower (Z) arm: cloak, core: shield
		</ul>
		<hr />
		<p>	The most important buildings are usually the middle ones in every category. Examples are mexes, the Light Laser Tower (LLT) in the defense- and the radar in the AUX-category.</p>
		<hr />
	</div><!close 6>

	<div id="7" class="">
		<p>	7) To build new units you need a factory (often referred to as a <i>LAB</i>). You can build one via the factory-section of the build menu.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_14.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_14.png" /></a>
		<p>	You can select the factory by either clicking on it directly or by clicking the factory's icon at the right edge of your screen.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_15.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_15.png" /></a>
		<p>	You can also select the factory by drawing a rectangle around it, but this will also select a unit, if the factory is currently producing one. Another way to select your factory is by browsing through your idle workers list, which includes factories provided they are idle too. To do so simply hold down the CTRL key and press B until your factory is selected.</p>
		<p>	Usually the first thing you do is make sure your factory is set to repeat building units over and over again, until it is either destroyed, or reclaimed. Check the factory icon on the right side of the screen. If it looks like this, the repeat command is active. If the little symbol is missing, it is not.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_16.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_16.png" /></a>
		<p>	To toggle the repeat command either left-click in the upper right corner of your factories icon, or the "Repeat" button in the command menu to the left.</p>
		<p>	You can add units to your factories production queue by left-clicking at the icon of the units you wish to build. The factory will then immediately start production. To remove a unit from the queue, simply right-click the units icon. The repeat option will allow your factory to keep producing units indefinitely at your chosen ratio. If you need a unit quickly, you can press alt while clicking and you will make that many units outside of the queued loop which will be made first. Shift click adds/removes 5 of the chosen unit, ctrl click 20, and ctrl+shift click 100. </p>
		<p>	A good start is to order your factory to produce one construction bot and around five raiders. (remember to put them on repeat)</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_17.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_17.png" /></a>
		<p>	As soon as a construction unit has been completed, it will move around the factory and start to assist it to speed up the production process of further units. (if factory guard widget is enabled)</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_18.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_18.png" /></a>
	</div><!close 7>

	<div id="8" class="">
		<p>	8) You can select multiple units of the same type on your screen by double-clicking one of them. You can also hold down CTRL and press Z to select <strong>all</strong> units of all the unit types you currently have selected.</p>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_19.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_19.png" /></a>
		<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_20.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_20.png" /></a>
	</div><!close 8>

	<div id="9" class="">
	<p>9) You can order units to move by simply right-clicking at a location. You can order units to attack by right clicking an enemy unit. Units will also automatically fire at enemies in range. Nearly all units can also shoot while moving. A very useful way to command units are custom-formations. You can hold down the right mouse button when having multiple units selected to draw a line or curve to order your units to spread out and proceed towards their position in the formation.</p> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_21.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_21.png" /></a> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_22.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_22.png" /></a> 
	<p>Hold down the SHIFT key while having units selected to take a look at their current command queue. While doing so you can also add new commands to your selected units, which will then process all commands one after the other.</p> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/attachment/wiki/NewbieGuide/guide2_23.png"><img class="border" width="400" src="http://trac.caspring.org/raw-attachment/wiki/NewbieGuide/guide2_23.png" /></a> 
	<p><br /> </p> 
	</div><!close 9>
</div><!close ch1>
<div id="ch2" class="">
	<h2 id="Chapter2:UnitRoles">Chapter 2: Unit Roles</h2> 
	<p><strong>Work in progress</strong> - pictures coming soon</p> 
	<p>Combat units in CA generally fall into one of several classes. Understanding these roles and knowing how best to use and combine them for maximum effect is the cornerstone of a victorious battle in CA.</p> 
	<p><i>Icons under titles indicate the role mapicon of that class. For further details, consult the <a class="wiki" href="http://trac.caspring.org/wiki/IconGuide">Icon Guide</a>.</i> </p> 
	<h3 id="PrimaryClasses">Primary Classes</h3> 
	<p><strong>Raider</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/raider.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/raider.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/raider.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/raider.png?format=raw" /></a><br /> 
	The raider personifies blitzkrieg tactics - sheer firepower and the speed needed to get it into the enemy's heartland. Raiders have the highest DPS per cost and speed of all the unit classes, but they also have the worst armor and range of the combat classes. The primary uses for raiders are harassment attacks to interfere with an enemy's economy, and brute-forcing a particularly weak point in the enemy's lines. They also come in handy for scouting, although a dedicated scout is better for the task.</p> 
	<p><i>Protip:</i> The Unit AI can automatically micro your raiders to jink enemy shots if you give them a fight order.</p> 
	<table class="wiki"> 
	<tr><td><strong>Use for:</strong></td><td><strong>Counter with:</strong> 
	</td></tr><tr><td>Early game rush<br />Armed reconnaissance<br />Flanking skirmisher/support units<br />Rushing through breaches in defense<br />Fast response vs. other raiders<br /> </td><td>LLTs<br />Antiswarm/riot units<br />Fast attack gunships<br />Area bombers<br /> 
	</td></tr></table> 
	<p><strong>Assault</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/assault.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/assault.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/assault.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/assault.png?format=raw" /></a><br /> 
	The mainline unit, the assault class is favored for its staying power and ease of use. Assault units emphasize great armor and decent speed; while their firepower is poor for cost and their range fairly mediocre, they generally survive long enough to do a fair bit of damage. As its name suggests, the assault class excels at attacking enemy strongpoints. Especially in the case of tanks, they make good general purpose battle units.</p> 
	<table class="wiki"> 
	<tr><td><strong>Use for:</strong></td><td><strong>Counter with:</strong> 
	</td></tr><tr><td>Frontal assault<br />Screening allied units<br />Pushing in the field<br />General confrontations<br /> </td><td>Micro'd raiders<br />Precision bombers<br />Gunships<br />Crawling bombs<br /> 
	</td></tr></table> 
	<p><strong>Skirmisher</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/skirm.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/skirm.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/skirm.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/skirm.png?format=raw" /></a><br /> 
	Skirmishers are like cavalry archers - fast low-defense units with good ranged capabilities. They support your forces by picking off enemies quickly and efficiently, before they can do damage. Skirms have thin armor, and rely on their speed and range (as well as the protection of nearby friendlies) for defense. The strength of the skirmisher lies in its ability to  shoot without fear of retaliation - always maximize this advantage by using the technique known as kiting (moving away as shorter-ranged enemies attempt to close the distance).</p> 
	<p><i>Protip:</i> Giving a Fight order to your skirms will have the Unit AI kite enemies automatically as needed.</p> 
	<table class="wiki"> 
	<tr><td><strong>Use for:</strong></td><td><strong>Counter with:</strong> 
	</td></tr><tr><td>Skirmishing with assaults<br />Countering unsupported compush<br />Harassing enemy forward positions<br />Countering riot spam<br />Picking off short-ranged turrets<br /> </td><td>Raiders<br />Crawling bombs (depends on skirm type)<br />Gunships, area bombers<br />Defenses that can outrange skirms<br />Defend on high ground
	</td></tr></table> 
	<p><strong>Riot</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/riot.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/riot.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/riot.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/riot.png?format=raw" /></a><br /> 
	The riot class excels in crowd control, slaying huge amounts of lighter units such as raiders. Units of this class will either have a high rate of fire or a large AoE, sometimes both. They also have high DPS values. On the flip side, riot units are slow and short-ranged, and are poorly suited for assaulting defenses (which get in a lot of free shots as the slow riot unit attempts to get close enough to fire) or fighting skirmisher groups (which will simply kite them).</p> 
	<p>Due to their high-velocity projectiles, some riot units can also pose a significant threat to attacking gunships.</p> 
	<table class="wiki"> 
	<tr><td><strong>Use for:</strong></td><td><strong>Counter with:</strong> 
	</td></tr><tr><td>Countering raider swarms<br />Protecting ranged units<br />Secondary AA (against gunships)<br /> </td><td>Skirmishers<br />Static defense<br />Outmaneuvering/bypassing them 
	</td></tr></table> 
	<p>Note that these classes are generalized; specific units will often have different properties that cause their behavior to deviate significantly from the general archetype!</p> 
	<h3 id="Secondaryclasses">Secondary classes</h3> 
	<p><strong>Artillery</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/arty.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/arty.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/arty.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/arty.png?format=raw" /></a><br /> 
	Artillery units are generally used to pick off enemy structures from a safe distance. Easily outranging static defenses, artillery can destroy them with impunity. Mobile units can usually dodge the fire of most (but not all) artillery, and artillery units tend to be completely helpless when attacked directly.</p> 
	<p><strong>Scout</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/scout.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/scout.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/scout.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/scout.png?format=raw" /></a><br /> 
	Scout units are just that - scouts. They have extreme speed and good perception, and their dirt-cheap cost makes them expendable - just as well considering that they have no armor to speak of whatsoever. Scouts tend to be only very lightly armed, but they can still kill a few undefended economy structures here and there if one isn't careful.</p> 
	<p><strong>Anti-Air</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/aa.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/aa.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/aa.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/aa.png?format=raw" /></a><br /> 
	Anti-air units exist for one purpose - defend your army from aircraft. Their high firepower and range allows them to destroy enemy aircraft before they can damage your forces, but they are of course useless against any other target.</p> 
	<p><strong>Support</strong><br /> 
	<a style="padding:0; border:none" href="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/support.png"><img class="border" width="64" alt="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/support.png" title="source:/trunk/tools/MapIconBuilder/MapIcons/2_Class/support.png" src="http://trac.caspring.org/browser/trunk/tools/MapIconBuilder/MapIcons/2_Class/support.png?format=raw" /></a><br /> 
	Support units fall into two categories: combat and non-combat. Combat or ranged support units generally offer specialized ranged firepower effective against specific units. Non-combat supporters do not participate in combat directly, but instead augment your force in various ways; the selection of such units available to the commander include mobile jammers, shield generators, spies, EMP attackers, and even the humble mobile radar.</p> 
</div><!close ch2>
<div id="ch3"></p> 
	<h2 id="Chapter3:BasicFieldOperations">Chapter 3: Basic Field Operations</h2> 
	<p>Now that you know what the units do, it's time to play a game. Here's how to get rolling once your commander spawns:</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_1.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_1.jpg" alt="http://licho.eu/alba/caguide/guide3_1.jpg" title="http://licho.eu/alba/caguide/guide3_1.jpg" /></a> 
	<p>1) You should be next to three or so metal spots. Start by placing a mex on the closest one.</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_2.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_2.jpg" alt="http://licho.eu/alba/caguide/guide3_2.jpg" title="http://licho.eu/alba/caguide/guide3_2.jpg" /></a> 
	<p>2) Depending on the map, the other two spots should be within a few seconds of walking your commander; move over and mex those as well, placing four solars as you go. If the spots are too far away, skip to step 3 and mex those spots later.</p> 
	<p>If you started on high ground (a plateau for instance), you can use wind instead of or along with solar, which provides more energy (especially on high areas) but is less reliable and prone to being raided.</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_3.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_3.jpg" alt="http://licho.eu/alba/caguide/guide3_3.jpg" title="http://licho.eu/alba/caguide/guide3_3.jpg" /></a> 
	<p>3) Build your factory. While pros have ways to start with heavy facs (walker/tank) or air, newbies should stick to the light factories (bot and vehicle). The easiest fac to start with is the Logos vehicle plant; it has a lot of strength and doesn't have to rely on special options (unlike Nova, bots and especially Nova bots.)</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_4.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_4.jpg" alt="http://licho.eu/alba/caguide/guide3_4.jpg" title="http://licho.eu/alba/caguide/guide3_4.jpg" /></a> 
	<p>Remember, only one factory at a time, and never leave it idle!</p> 
	<p>4) Your commander should have a little boost left; deploy an LLT to deter raiders. Place it in a spot where it can cover as much of your base as possible. It may also be a good idea to make a radar tower; radar is essential to keeping track of enemy movements.</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_5.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_5.jpg" alt="http://licho.eu/alba/caguide/guide3_5.jpg" title="http://licho.eu/alba/caguide/guide3_5.jpg" /></a> 
	<p>5) Put that factory to work. Start by making a constructor or two; use them to expand outwards, claiming mexes. Buy a pair of Weasels (or equivalent scout if you started another factory), and have them scout outwards. Remember that you can assist the factory with construction units (including the commander) to build stuff faster (give it a guard order on the fac). Now would be a good time to build a couple more solars.</p> 
	<p>6) Now buy 3-5 raiders (in this case, Instigators). This will be your mobile force; you can use it to raid the enemy, or establish a forward perimeter. Have the Weasels check on the enemy base; depending on what they run into, you might be able to conduct a surprise raid with your gators and damage some of his economy. When raiding, avoid LLTs and the enemy commander, and go for vulnerable economic targets (wind generators are best, mexes are great pickings as well).</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_6.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_6.jpg" alt="http://licho.eu/alba/caguide/guide3_6.jpg" title="http://licho.eu/alba/caguide/guide3_6.jpg" /></a> 
	<p>7) Make another constructor. You're probably stalling metal by this stage, so have the constructor take over assisting the factory and move your commander forward towards the enemy, mexing any unclaimed mex spots. Remember, though: your commander is not Superman. If you send him into unfriendly territory alone, he <i>will</i> get his ass kicked. Have some mobile units or turrets nearby at all times.</p> 
	<p>Keep making energy structures to keep up with your metal production. For maximum efficiency, your energy output should always exceed your metal output.</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_7.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_7.jpg" alt="http://licho.eu/alba/caguide/guide3_7.jpg" title="http://licho.eu/alba/caguide/guide3_7.jpg" /></a> 
	<p><strong><i>Don't stop moving forward until you encounter the enemy lines.</i></strong> This cannot be emphasized enough: you can never win by staying in your base and digging in.</p> 
	<p>8) Now it's time to consider what to do with your factory. The two standard options are:</p> 
	<ul><li><strong>More raiders:</strong> This gives you a fast-moving, powerful attack group that can cover wide areas of territory and hit weak points. A good choice on large maps. Just don't try to rush LLTs and antiswarm/riot units with it.
	<ul><li>6-15 Glaives, Bandits, Flashes or Instigators, with a few scouts
	</ul></ul><a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_8.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_8.jpg" alt="http://licho.eu/alba/caguide/guide3_8.jpg" title="http://licho.eu/alba/caguide/guide3_8.jpg" /></a> 
	<ul><li><strong>Skirmisher line:</strong> This option allows you to roll back enemy LLT expansions effectively, although it is not as mobile as a raider force. Works best when accompanied by a commander (to secure claimed territory with LLTs, and repair damaged units). A few riot units should be included to defend against raiders.
	<ul><li>4-6 Rockos, 2-3 Warriors
	<li>4-6 Storms, 2 Outlaws or 4-8 Thuds
	<li>4-6 Januses/Samsons, 6 Flashes or 4 Stumpies
	<li>4-6 Slashers, 2-3 Levelers
	</ul></ul><a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_9.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_9.jpg" alt="http://licho.eu/alba/caguide/guide3_9.jpg" title="http://licho.eu/alba/caguide/guide3_9.jpg" /></a> 
	<p>Depending on map size, you should be encountering your enemy's expansion around this time. Use appropriate methods to roll him back or delay his buildup. Deploy radar towers and a few defense structures as you advance. Don't forget to keep making solars to support your increased metal throughput (but don't make this the sole focus of your economy either!).</p> 
	<p>9) Keep making units and expanding your economy. Skirmishers and artillery can be used for destroying static emplacements; assault units are good for breakthroughs and general combat, while riot units are ideal for mobile defense. Remember to reclaim as much wreckage as you can; the extra metal makes all the difference. If you are stalling, reclaim metal or divert cons to energy production as needed; if you are excessing, make more constructors and use them to build stuff or assist factories (plopping down a nano or two works well).</p> 
	<a style="padding:0; border:none" href="http://licho.eu/alba/caguide/guide3_10.jpg"><img class="border" src="http://licho.eu/alba/caguide/guide3_10.jpg" alt="http://licho.eu/alba/caguide/guide3_10.jpg" title="http://licho.eu/alba/caguide/guide3_10.jpg" /></a> 
	<p>Never dig in with lots of defenses until you've collided with the enemy and are stalemating; then make a few LLTs or antiswarm turrets and a HLT (<i>only one</i>) to create a safe zone which you can use as a staging area. Avoid spamming defenses all over the map or walking porc; skirmisher and artillery pushes will stomp on you easily. Just make more mobile units.</p> 
	<p>Don't forget your anti-air!</p> 
</div><!close ch3>

<div id="wrapup" class="">
	<p>	10) You're on your own from here. Keep playing aggressively, attacking weak points constantly and putting your opponent on the defensive. However, don't give him free wreck metal by running headlong into defenses - use your discretion when attacking. Don't forget to make use of scouts; knowing your opponent is half the battle.</p>
	<p>	Stay focused and on the ball, and the path to victory shall be in clear sight.</p>
	<p>	<strong>Questions</strong> </p>
	<ul><li><strong><i>I think tank/walker start is very good as the units are much stronger than bot/vehicle! Why not T/W start? </i></strong> 
	<ul><li><a class="ext-link" href="http://objection.mrdictionary.net/go.php?n=3944332"><span class="icon"></span>My response</a> 
	</ul><li><strong><i>OMG why only one HLT? I like 2! </i></strong> 
	<ul><li><a class="ext-link" href="http://objection.mrdictionary.net/go.php?n=3077785"><span class="icon"></span>My response</a> 
	</ul><li><strong><i>Why no storages? They're good for holding all the metal I'm collecting! </i></strong> 
	<ul><li><a class="ext-link" href="http://objection.mrdictionary.net/go.php?n=3944379"><span class="icon"></span>My response</a> 
	</ul><li><strong><i>Why can't I stay in my base and make energy for overdrive? It's nice and cozy in here...</i></strong> 
	<ul><li><a class="ext-link" href="http://objection.mrdictionary.net/go.php?n=3944510"><span class="icon"></span>My response</a> 
	</ul></ul><h2 id="MoreReading">More Reading</h2> 
	<ul><li><strong><a class="wiki" href="http://trac.caspring.org/wiki/Manual">Manual</a></strong> 
	<ul><li><a class="wiki" href="http://trac.caspring.org/wiki/CustomKeys">Custom Keys</a> 
	<li><a class="wiki" href="http://trac.caspring.org/wiki/EconomyGuide">Economy Guide</a> 
	<li><a class="wiki" href="http://trac.caspring.org/wiki/AggressionGuide">Aggression Guide</a> 
	<li><a class="wiki" href="http://trac.caspring.org/wiki/StrategyTreatise">Strategy Treatise</a> 
	</ul></ul>
</div><!close wrapup>
</div><!close guide>