<div>
  <h2>Welcome to Zero-K</h2>

  To learn basics, please read <a href='/Wiki.mvc/NewbieGuide'>Newbie Guide</a><br/><br/>

  Try game in single player first. Recommended missions are:<br/><br/>

  * <a href="spring://http://@start_script_mission:2v1">2v1 - play with AI against another AI</a><br/>
  * <a href="spring://http://@start_script_mission:Very%20easy%20chickens">Very easy chickens - defend yourself from hordes of chicken aliens</a><br/>
  * <a href='spring://http://@start_script_mission:sandbox'>Sandbox - just test the GUI and learn your own units</a><br/>
  <br/><br/>
  
  <h2>TroubleShooting</h2>

  * Please make sure your graphic drivers are updated to latest! <br/>
  * In case of game crashes disable shadows, lua shaders, water, pixel buffer and enable compressed textures.<br/>
</div>