//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpringDownloader.StartTab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SinglePlayerStartScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SinglePlayerStartScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpringDownloader.StartTab.SinglePlayerStartScripts", typeof(SinglePlayerStartScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=TitanDuel.smf;
        ///	Maphash=3968749533;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=keepequal;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspeedmult=1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_1v1 {
            get {
                return ResourceManager.GetString("ca_1v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=%MAP%;
        ///	Maphash=1827208863;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=mapdefault;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspeedmult=1;
        ///		cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_2v1 {
            get {
                return ResourceManager.GetString("ca_2v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=%MAP%;
        ///	Maphash=3606544977;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=keepequal;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspeedmult=1;
        ///		cra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_chickeneasy {
            get {
                return ResourceManager.GetString("ca_chickeneasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=Chicken_Roast_v1.smf;
        ///	Maphash=3695869842;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=keepequal;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_chickennormal {
            get {
                return ResourceManager.GetString("ca_chickennormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=%MAP%;
        ///	Maphash=275334332;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=keepequal;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspeedmult=1;
        ///		crat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_chickenveryeasy {
            get {
                return ResourceManager.GetString("ca_chickenveryeasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///	Mapname=%MAP%;
        ///	[modoptions]
        ///	{
        ///		MaxUnits=500;
        ///		GameMode=0;
        ///		fixedallies=1;
        ///		minspeed=0.5;
        ///		maxspeed=2;
        ///		disablemapdamage=0;
        ///		camode=normal;
        ///		hilltime=10;
        ///		gracetime=2;
        ///		commtype=default;
        ///		startingresourcetype=facplopboost;
        ///		shuffle=off;
        ///		noceasefire=0;
        ///		sharemode=teammates;
        ///		typemapsetting=keepequal;
        ///		waterlevel=0;
        ///		metalmult=1;
        ///		energymult=1;
        ///		minwind=0;
        ///		maxwind=2.5;
        ///		terracostmult=1;
        ///		damagemult=1;
        ///		unitspeedmult=1;
        ///		cratermult=1;
        ///		reducedq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ca_sandbox {
            get {
                return ResourceManager.GetString("ca_sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GAME]
        ///{
        ///        GameType=%MOD%;
        ///        Mapname=%MAP%;
        ///        [MODOPTIONS]
        ///        {
        ///                GameMode=3;
        ///                ghostedbuildings=1;
        ///                fixedallies=0;
        ///                MaxUnits=512;
        ///                MinSpeed=0.1;
        ///                MaxSpeed=10;
        ///                StartMetal=1024;
        ///                StartEnergy=1024;
        ///                ViewPoint=&quot;{px=3815,py=256,pz=2251,rz=0,dx=-0.614,dy=-0.302,name=&quot;fps&quot;,ry=3.84,rx=-0.307,mode=0,dz=-0.73,oldHeight=176}&quot;;
        ///        }
        ///        Ho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kp_script {
            get {
                return ResourceManager.GetString("kp_script", resourceCulture);
            }
        }
    }
}
