//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Galaxy xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MapNames&gt;
        ///    &lt;string&gt;2_Continents_Remake.smf&lt;/string&gt;
        ///    &lt;string&gt;2_Mountains_Battlefield.smf&lt;/string&gt;
        ///    &lt;string&gt;2_Valleys-v04.smf&lt;/string&gt;
        ///    &lt;string&gt;AavikkoV2.smf&lt;/string&gt;
        ///    &lt;string&gt;Altored_Arctic.smf&lt;/string&gt;
        ///    &lt;string&gt;Altored_Divide.smf&lt;/string&gt;
        ///    &lt;string&gt;AmazonDeltav20.smf&lt;/string&gt;
        ///    &lt;string&gt;Archers_Valley_v5.smf&lt;/string&gt;
        ///    &lt;strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string galaxy {
            get {
                return ResourceManager.GetString("galaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ServerState xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Accounts&gt;
        ///    &lt;item&gt;
        ///      &lt;key&gt;
        ///        &lt;string&gt;4pynqx&lt;/string&gt;
        ///      &lt;/key&gt;
        ///      &lt;value&gt;
        ///        &lt;Hash&gt;
        ///          &lt;AsString&gt;06d49632c9dc9bcb62aeaef99612ba6b&lt;/AsString&gt;
        ///        &lt;/Hash&gt;
        ///      &lt;/value&gt;
        ///    &lt;/item&gt;
        ///    &lt;item&gt;
        ///      &lt;key&gt;
        ///        &lt;string&gt;r285ao&lt;/string&gt;
        ///      &lt;/key&gt;
        ///      &lt;value&gt;
        ///        &lt;Hash&gt;
        ///          &lt;AsString&gt;eda5c582789e56fa8eb0fa8f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string serverstate {
            get {
                return ResourceManager.GetString("serverstate", resourceCulture);
            }
        }
    }
}
