<?xml version="1.0" encoding="utf-8"?>
<Database Name="MissionEditorServer" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=planet-wars.eu,100;Initial Catalog=MissionEditorServer;Persist Security Info=True;User ID=mission_editor" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EditorServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nick" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Mission_Comment" Member="Mission" ThisKey="MissionID" OtherKey="MissionID" Type="Mission" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rating" Member="Ratings">
    <Type Name="Rating">
      <Column Name="IP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rating" Member="Rating1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MissionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Mission_Rating" Member="Mission" ThisKey="MissionID" OtherKey="MissionID" Type="Mission" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Score" Member="Scores">
    <Type Name="Score">
      <Column Name="MissionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Member="Score1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeSeconds" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Mission_Score" Member="Mission" ThisKey="MissionID" OtherKey="MissionID" Type="Mission" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mission" Member="Missions">
    <Type Name="Mission">
      <Column Name="MissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Map" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mutator" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DownloadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastCommentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rating" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoringMethod" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TopScoreLine" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SpringVersion" Type="System.String" DbType="nvarchar(20)" CanBeNull="true" />
      <Column Name="MissionEditorVersion" Type="System.String" DbType="nvarchar(20)" CanBeNull="true" />
      <Association Name="Mission_Comment" Member="Comments" ThisKey="MissionID" OtherKey="MissionID" Type="Comment" />
      <Association Name="Mission_Rating" Member="Ratings" ThisKey="MissionID" OtherKey="MissionID" Type="Rating" />
      <Association Name="Mission_Score" Member="Scores" ThisKey="MissionID" OtherKey="MissionID" Type="Score" />
    </Type>
  </Table>
</Database>