//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRegistrator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistratorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistratorRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRegistrator.RegistratorRes", typeof(RegistratorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle for PlanetXVII-v01
        ///Adamantine Mountain 2
        ///Avalanche v3.1
        ///Wanderlust v03
        ///The river Nix 20
        ///Tabula-v6.1
        ///AlienDesert
        ///Quicksilver 1.1
        ///BlueBend-v01
        ///Red Comet v1.3
        ///Apophis v2_3
        ///Altair_Crossing_v3
        ///DunePatrol_wip_v03
        ///Fields_Of_Isis
        ///Violence_4.2
        ///IsisDelta_v02
        ///Tombstone Desert V2
        ///Archers_Valley_v6
        ///Otago 1.4
        ///Iced Coffee v4.3
        ///TheBeachBeta
        ///Onyx Cauldron 1.9
        ///Rapids_v1
        ///Malibu Beach v1
        ///Cull
        ///ScorpioBattleground
        ///AquariusCrossing
        ///BellicoseIslands_ZK-v01
        ///Paradise Lost v2
        ///IslandTest
        ///Valles_Marineris_v2
        ///Colorado_v1
        ///Trojan H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string campaignMaps {
            get {
                return ResourceManager.GetString("campaignMaps", resourceCulture);
            }
        }
    }
}
