//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroKLobby.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mission", Namespace="http://schemas.datacontract.org/2004/07/ZkData")]
    [System.SerializableAttribute()]
    public partial class Mission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZeroKLobby.ServiceReference.Binary MutatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZeroKLobby.ServiceReference.Binary ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownloadCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoringMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopScoreLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionEditorVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpringVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependenciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampaignIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZeroKLobby.ServiceReference.MissionSlot[] MissionSlotsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionID {
            get {
                return this.MissionIDField;
            }
            set {
                if ((this.MissionIDField.Equals(value) != true)) {
                    this.MissionIDField = value;
                    this.RaisePropertyChanged("MissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Mod {
            get {
                return this.ModField;
            }
            set {
                if ((object.ReferenceEquals(this.ModField, value) != true)) {
                    this.ModField = value;
                    this.RaisePropertyChanged("Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ZeroKLobby.ServiceReference.Binary Mutator {
            get {
                return this.MutatorField;
            }
            set {
                if ((object.ReferenceEquals(this.MutatorField, value) != true)) {
                    this.MutatorField = value;
                    this.RaisePropertyChanged("Mutator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ZeroKLobby.ServiceReference.Binary Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int DownloadCount {
            get {
                return this.DownloadCountField;
            }
            set {
                if ((this.DownloadCountField.Equals(value) != true)) {
                    this.DownloadCountField = value;
                    this.RaisePropertyChanged("DownloadCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> ModifiedTime {
            get {
                return this.ModifiedTimeField;
            }
            set {
                if ((this.ModifiedTimeField.Equals(value) != true)) {
                    this.ModifiedTimeField = value;
                    this.RaisePropertyChanged("ModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ScoringMethod {
            get {
                return this.ScoringMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoringMethodField, value) != true)) {
                    this.ScoringMethodField = value;
                    this.RaisePropertyChanged("ScoringMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string TopScoreLine {
            get {
                return this.TopScoreLineField;
            }
            set {
                if ((object.ReferenceEquals(this.TopScoreLineField, value) != true)) {
                    this.TopScoreLineField = value;
                    this.RaisePropertyChanged("TopScoreLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string MissionEditorVersion {
            get {
                return this.MissionEditorVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionEditorVersionField, value) != true)) {
                    this.MissionEditorVersionField = value;
                    this.RaisePropertyChanged("MissionEditorVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string SpringVersion {
            get {
                return this.SpringVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.SpringVersionField, value) != true)) {
                    this.SpringVersionField = value;
                    this.RaisePropertyChanged("SpringVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Dependencies {
            get {
                return this.DependenciesField;
            }
            set {
                if ((object.ReferenceEquals(this.DependenciesField, value) != true)) {
                    this.DependenciesField = value;
                    this.RaisePropertyChanged("Dependencies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string TokenCondition {
            get {
                return this.TokenConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenConditionField, value) != true)) {
                    this.TokenConditionField = value;
                    this.RaisePropertyChanged("TokenCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<int> CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                if ((this.CampaignIDField.Equals(value) != true)) {
                    this.CampaignIDField = value;
                    this.RaisePropertyChanged("CampaignID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<int> AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string ModOptions {
            get {
                return this.ModOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModOptionsField, value) != true)) {
                    this.ModOptionsField = value;
                    this.RaisePropertyChanged("ModOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public ZeroKLobby.ServiceReference.MissionSlot[] MissionSlots {
            get {
                return this.MissionSlotsField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionSlotsField, value) != true)) {
                    this.MissionSlotsField = value;
                    this.RaisePropertyChanged("MissionSlots");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissionSlot", Namespace="http://schemas.datacontract.org/2004/07/ZkData")]
    [System.SerializableAttribute()]
    public partial class MissionSlot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHumanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AiShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AiVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionID {
            get {
                return this.MissionIDField;
            }
            set {
                if ((this.MissionIDField.Equals(value) != true)) {
                    this.MissionIDField = value;
                    this.RaisePropertyChanged("MissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamID {
            get {
                return this.TeamIDField;
            }
            set {
                if ((this.TeamIDField.Equals(value) != true)) {
                    this.TeamIDField = value;
                    this.RaisePropertyChanged("TeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int AllyID {
            get {
                return this.AllyIDField;
            }
            set {
                if ((this.AllyIDField.Equals(value) != true)) {
                    this.AllyIDField = value;
                    this.RaisePropertyChanged("AllyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsHuman {
            get {
                return this.IsHumanField;
            }
            set {
                if ((this.IsHumanField.Equals(value) != true)) {
                    this.IsHumanField = value;
                    this.RaisePropertyChanged("IsHuman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsRequired {
            get {
                return this.IsRequiredField;
            }
            set {
                if ((this.IsRequiredField.Equals(value) != true)) {
                    this.IsRequiredField = value;
                    this.RaisePropertyChanged("IsRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string AiShortName {
            get {
                return this.AiShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AiShortNameField, value) != true)) {
                    this.AiShortNameField = value;
                    this.RaisePropertyChanged("AiShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string AiVersion {
            get {
                return this.AiVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.AiVersionField, value) != true)) {
                    this.AiVersionField = value;
                    this.RaisePropertyChanged("AiVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string AllyName {
            get {
                return this.AllyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AllyNameField, value) != true)) {
                    this.AllyNameField = value;
                    this.RaisePropertyChanged("AllyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IMissionService")]
    public interface IMissionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionService/DeleteMission", ReplyAction="http://tempuri.org/IMissionService/DeleteMissionResponse")]
        void DeleteMission(int missionID, string author, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissionService/DeleteMission", ReplyAction="http://tempuri.org/IMissionService/DeleteMissionResponse")]
        System.IAsyncResult BeginDeleteMission(int missionID, string author, string password, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteMission(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionService/GetMission", ReplyAction="http://tempuri.org/IMissionService/GetMissionResponse")]
        ZeroKLobby.ServiceReference.Mission GetMission(string missionName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissionService/GetMission", ReplyAction="http://tempuri.org/IMissionService/GetMissionResponse")]
        System.IAsyncResult BeginGetMission(string missionName, System.AsyncCallback callback, object asyncState);
        
        ZeroKLobby.ServiceReference.Mission EndGetMission(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionService/GetMissionByID", ReplyAction="http://tempuri.org/IMissionService/GetMissionByIDResponse")]
        ZeroKLobby.ServiceReference.Mission GetMissionByID(int missionID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissionService/GetMissionByID", ReplyAction="http://tempuri.org/IMissionService/GetMissionByIDResponse")]
        System.IAsyncResult BeginGetMissionByID(int missionID, System.AsyncCallback callback, object asyncState);
        
        ZeroKLobby.ServiceReference.Mission EndGetMissionByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionService/ListMissionInfos", ReplyAction="http://tempuri.org/IMissionService/ListMissionInfosResponse")]
        ZeroKLobby.ServiceReference.Mission[] ListMissionInfos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissionService/ListMissionInfos", ReplyAction="http://tempuri.org/IMissionService/ListMissionInfosResponse")]
        System.IAsyncResult BeginListMissionInfos(System.AsyncCallback callback, object asyncState);
        
        ZeroKLobby.ServiceReference.Mission[] EndListMissionInfos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionService/SendMission", ReplyAction="http://tempuri.org/IMissionService/SendMissionResponse")]
        void SendMission(ZeroKLobby.ServiceReference.Mission mission, string author, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissionService/SendMission", ReplyAction="http://tempuri.org/IMissionService/SendMissionResponse")]
        System.IAsyncResult BeginSendMission(ZeroKLobby.ServiceReference.Mission mission, string author, string password, System.AsyncCallback callback, object asyncState);
        
        void EndSendMission(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMissionServiceChannel : ZeroKLobby.ServiceReference.IMissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ZeroKLobby.ServiceReference.Mission Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ZeroKLobby.ServiceReference.Mission)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMissionByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMissionByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ZeroKLobby.ServiceReference.Mission Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ZeroKLobby.ServiceReference.Mission)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListMissionInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListMissionInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ZeroKLobby.ServiceReference.Mission[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ZeroKLobby.ServiceReference.Mission[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MissionServiceClient : System.ServiceModel.ClientBase<ZeroKLobby.ServiceReference.IMissionService>, ZeroKLobby.ServiceReference.IMissionService {
        
        private BeginOperationDelegate onBeginDeleteMissionDelegate;
        
        private EndOperationDelegate onEndDeleteMissionDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteMissionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMissionDelegate;
        
        private EndOperationDelegate onEndGetMissionDelegate;
        
        private System.Threading.SendOrPostCallback onGetMissionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMissionByIDDelegate;
        
        private EndOperationDelegate onEndGetMissionByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetMissionByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginListMissionInfosDelegate;
        
        private EndOperationDelegate onEndListMissionInfosDelegate;
        
        private System.Threading.SendOrPostCallback onListMissionInfosCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendMissionDelegate;
        
        private EndOperationDelegate onEndSendMissionDelegate;
        
        private System.Threading.SendOrPostCallback onSendMissionCompletedDelegate;
        
        public MissionServiceClient() {
        }
        
        public MissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteMissionCompleted;
        
        public event System.EventHandler<GetMissionCompletedEventArgs> GetMissionCompleted;
        
        public event System.EventHandler<GetMissionByIDCompletedEventArgs> GetMissionByIDCompleted;
        
        public event System.EventHandler<ListMissionInfosCompletedEventArgs> ListMissionInfosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendMissionCompleted;
        
        public void DeleteMission(int missionID, string author, string password) {
            base.Channel.DeleteMission(missionID, author, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteMission(int missionID, string author, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteMission(missionID, author, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteMission(System.IAsyncResult result) {
            base.Channel.EndDeleteMission(result);
        }
        
        private System.IAsyncResult OnBeginDeleteMission(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int missionID = ((int)(inValues[0]));
            string author = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return this.BeginDeleteMission(missionID, author, password, callback, asyncState);
        }
        
        private object[] OnEndDeleteMission(System.IAsyncResult result) {
            this.EndDeleteMission(result);
            return null;
        }
        
        private void OnDeleteMissionCompleted(object state) {
            if ((this.DeleteMissionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteMissionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteMissionAsync(int missionID, string author, string password) {
            this.DeleteMissionAsync(missionID, author, password, null);
        }
        
        public void DeleteMissionAsync(int missionID, string author, string password, object userState) {
            if ((this.onBeginDeleteMissionDelegate == null)) {
                this.onBeginDeleteMissionDelegate = new BeginOperationDelegate(this.OnBeginDeleteMission);
            }
            if ((this.onEndDeleteMissionDelegate == null)) {
                this.onEndDeleteMissionDelegate = new EndOperationDelegate(this.OnEndDeleteMission);
            }
            if ((this.onDeleteMissionCompletedDelegate == null)) {
                this.onDeleteMissionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteMissionCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteMissionDelegate, new object[] {
                        missionID,
                        author,
                        password}, this.onEndDeleteMissionDelegate, this.onDeleteMissionCompletedDelegate, userState);
        }
        
        public ZeroKLobby.ServiceReference.Mission GetMission(string missionName) {
            return base.Channel.GetMission(missionName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMission(string missionName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMission(missionName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ZeroKLobby.ServiceReference.Mission EndGetMission(System.IAsyncResult result) {
            return base.Channel.EndGetMission(result);
        }
        
        private System.IAsyncResult OnBeginGetMission(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string missionName = ((string)(inValues[0]));
            return this.BeginGetMission(missionName, callback, asyncState);
        }
        
        private object[] OnEndGetMission(System.IAsyncResult result) {
            ZeroKLobby.ServiceReference.Mission retVal = this.EndGetMission(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMissionCompleted(object state) {
            if ((this.GetMissionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMissionCompleted(this, new GetMissionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMissionAsync(string missionName) {
            this.GetMissionAsync(missionName, null);
        }
        
        public void GetMissionAsync(string missionName, object userState) {
            if ((this.onBeginGetMissionDelegate == null)) {
                this.onBeginGetMissionDelegate = new BeginOperationDelegate(this.OnBeginGetMission);
            }
            if ((this.onEndGetMissionDelegate == null)) {
                this.onEndGetMissionDelegate = new EndOperationDelegate(this.OnEndGetMission);
            }
            if ((this.onGetMissionCompletedDelegate == null)) {
                this.onGetMissionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMissionCompleted);
            }
            base.InvokeAsync(this.onBeginGetMissionDelegate, new object[] {
                        missionName}, this.onEndGetMissionDelegate, this.onGetMissionCompletedDelegate, userState);
        }
        
        public ZeroKLobby.ServiceReference.Mission GetMissionByID(int missionID) {
            return base.Channel.GetMissionByID(missionID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMissionByID(int missionID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMissionByID(missionID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ZeroKLobby.ServiceReference.Mission EndGetMissionByID(System.IAsyncResult result) {
            return base.Channel.EndGetMissionByID(result);
        }
        
        private System.IAsyncResult OnBeginGetMissionByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int missionID = ((int)(inValues[0]));
            return this.BeginGetMissionByID(missionID, callback, asyncState);
        }
        
        private object[] OnEndGetMissionByID(System.IAsyncResult result) {
            ZeroKLobby.ServiceReference.Mission retVal = this.EndGetMissionByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMissionByIDCompleted(object state) {
            if ((this.GetMissionByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMissionByIDCompleted(this, new GetMissionByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMissionByIDAsync(int missionID) {
            this.GetMissionByIDAsync(missionID, null);
        }
        
        public void GetMissionByIDAsync(int missionID, object userState) {
            if ((this.onBeginGetMissionByIDDelegate == null)) {
                this.onBeginGetMissionByIDDelegate = new BeginOperationDelegate(this.OnBeginGetMissionByID);
            }
            if ((this.onEndGetMissionByIDDelegate == null)) {
                this.onEndGetMissionByIDDelegate = new EndOperationDelegate(this.OnEndGetMissionByID);
            }
            if ((this.onGetMissionByIDCompletedDelegate == null)) {
                this.onGetMissionByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMissionByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetMissionByIDDelegate, new object[] {
                        missionID}, this.onEndGetMissionByIDDelegate, this.onGetMissionByIDCompletedDelegate, userState);
        }
        
        public ZeroKLobby.ServiceReference.Mission[] ListMissionInfos() {
            return base.Channel.ListMissionInfos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListMissionInfos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListMissionInfos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ZeroKLobby.ServiceReference.Mission[] EndListMissionInfos(System.IAsyncResult result) {
            return base.Channel.EndListMissionInfos(result);
        }
        
        private System.IAsyncResult OnBeginListMissionInfos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginListMissionInfos(callback, asyncState);
        }
        
        private object[] OnEndListMissionInfos(System.IAsyncResult result) {
            ZeroKLobby.ServiceReference.Mission[] retVal = this.EndListMissionInfos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListMissionInfosCompleted(object state) {
            if ((this.ListMissionInfosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListMissionInfosCompleted(this, new ListMissionInfosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListMissionInfosAsync() {
            this.ListMissionInfosAsync(null);
        }
        
        public void ListMissionInfosAsync(object userState) {
            if ((this.onBeginListMissionInfosDelegate == null)) {
                this.onBeginListMissionInfosDelegate = new BeginOperationDelegate(this.OnBeginListMissionInfos);
            }
            if ((this.onEndListMissionInfosDelegate == null)) {
                this.onEndListMissionInfosDelegate = new EndOperationDelegate(this.OnEndListMissionInfos);
            }
            if ((this.onListMissionInfosCompletedDelegate == null)) {
                this.onListMissionInfosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListMissionInfosCompleted);
            }
            base.InvokeAsync(this.onBeginListMissionInfosDelegate, null, this.onEndListMissionInfosDelegate, this.onListMissionInfosCompletedDelegate, userState);
        }
        
        public void SendMission(ZeroKLobby.ServiceReference.Mission mission, string author, string password) {
            base.Channel.SendMission(mission, author, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendMission(ZeroKLobby.ServiceReference.Mission mission, string author, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendMission(mission, author, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSendMission(System.IAsyncResult result) {
            base.Channel.EndSendMission(result);
        }
        
        private System.IAsyncResult OnBeginSendMission(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ZeroKLobby.ServiceReference.Mission mission = ((ZeroKLobby.ServiceReference.Mission)(inValues[0]));
            string author = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return this.BeginSendMission(mission, author, password, callback, asyncState);
        }
        
        private object[] OnEndSendMission(System.IAsyncResult result) {
            this.EndSendMission(result);
            return null;
        }
        
        private void OnSendMissionCompleted(object state) {
            if ((this.SendMissionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendMissionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendMissionAsync(ZeroKLobby.ServiceReference.Mission mission, string author, string password) {
            this.SendMissionAsync(mission, author, password, null);
        }
        
        public void SendMissionAsync(ZeroKLobby.ServiceReference.Mission mission, string author, string password, object userState) {
            if ((this.onBeginSendMissionDelegate == null)) {
                this.onBeginSendMissionDelegate = new BeginOperationDelegate(this.OnBeginSendMission);
            }
            if ((this.onEndSendMissionDelegate == null)) {
                this.onEndSendMissionDelegate = new EndOperationDelegate(this.OnEndSendMission);
            }
            if ((this.onSendMissionCompletedDelegate == null)) {
                this.onSendMissionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMissionCompleted);
            }
            base.InvokeAsync(this.onBeginSendMissionDelegate, new object[] {
                        mission,
                        author,
                        password}, this.onEndSendMissionDelegate, this.onSendMissionCompletedDelegate, userState);
        }
    }
}
