// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ZkData.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CampaignPlanetIndexReorder2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampaignPlanetIndexReorder2));
        
        string IMigrationMetadata.Id
        {
            get { return "201501031338090_CampaignPlanetIndexReorder2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
