using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ModelBase
{
	public partial class WebForm4 : System.Web.UI.Page
	{
		protected void Page_Load(object sender, EventArgs e)
		{
			if (!IsPostBack) {
				if (Global.LoggedUser != null && Global.LoggedUser.IsAdmin) {
					GridView1.ShowFooter = true;
					GridView1.AutoGenerateEditButton = true;
					GridView1.AutoGenerateDeleteButton = true;
				} else {
					GridView1.ShowFooter = false;
					GridView1.AutoGenerateEditButton = false;
					GridView1.AutoGenerateDeleteButton = false;
				}

			}

		}

		protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
		{
			if (e.CommandName=="Insert") {
				var tb = (TextBox) GridView1.FooterRow.FindControl("tbInsertName");
				
				
				LinqDataSource1.Insert(new Dictionary<string, string>() { { "Name", tb.Text } });
				tb.Text = "";
				GridView1.DataBind();
			}
		}
	}
}
