<div>
  <h2>Welcome to Zero-K</h2>
  
  <img src='/img/zk_logo.png' width='100%' height='100%' alt='alternative' /><br />

  To learn basics, please read <a href='/Wiki.mvc/NewbieGuide'>Newbie Guide</a> and inform yourself by reading the <a href='/Wiki.mvc/FAQ'>FAQ</a>.<br/><br/>
  
  Try game in single player first to gain some experiences with the game. Recommended missions are:<br/><br/>

  <ul style="list-style-image:url(/img/bullet.png);">

    <li> <a href='spring://http://@start_script_mission:sandbox'>Sandbox</a> - just test the GUI and learn your own units</li>
    <li> <a href="spring://http://@start_script_mission:2v1">2v1</a> - play with AI against another AI</li>
    <li> <a href="spring://http://@start_script_mission:Very%20easy%20chickens">Very easy chickens</a> - defend yourself from hordes of chicken aliens</li>
     
  </ul>
  
  <h2>TroubleShooting</h2>

  <ul style="list-style-image:url(/img/bullet.png);">

    <li> Please make sure your graphic drivers are updated to latest! </li>
    <li> In case of game crashes disable shadows, lua shaders, water, pixel buffer and enable compressed textures. </li>
    <li> <a href='http://docs.google.com/View?id=ajkvvmht466g_73gmsdwd8r'>Lobby help</a> </li>
    <li> Make sure you read the <a href='/Wiki.mvc/FAQ'>FAQ</a>. </li>
    <li> Post a new thread in our <a href='/Forum.mvc'>forum</a>. </li>

  </ul>
  
</div>