<div>
  <h2>Welcome to Zero-K</h2>

  To learn basics, please read <a href='/Wiki.mvc/NewbieGuide'>Newbie Guide</a><br/><br/>

  Try game in single player first. Recommended missions are:<br/><br/>

  * <a href="spring://http://@start_script_mission:2v1">2v1</a> - play with AI against another AI<br/>
  * <a href="spring://http://@start_script_mission:Very%20easy%20chickens">Very easy chickens</a> - defend yourself from hordes of chicken aliens<br/>
  * <a href='spring://http://@start_script_mission:sandbox'>Sandbox</a> - just test the GUI and learn your own units<br/>
  <br/><br/>
  
  <h2>TroubleShooting</h2>

  * Please make sure your graphic drivers are updated to latest! <br/>
  * In case of game crashes disable shadows, lua shaders, water, pixel buffer and enable compressed textures.<br/>
  * <a href='http://docs.google.com/View?id=ajkvvmht466g_73gmsdwd8r'>Lobby help</a><br/>
</div>