<div>  
  <img src='/img/zk_logo.png' width='100%' height='100%' alt='alternative' /><br />

  <h2>Welcome to Zero-K</h2>
  
  To learn basics, please read <a href='/Wiki/NewbieGuide'>Newbie Guide</a> and inform yourself by reading the <a href='/Wiki.mvc/FAQ'>FAQ</a>.<br/><br/>
  
  Try game in single player first to gain some experiences with the game. Recommended missions are:<br/><br/>

  <ul style="list-style-image:url(/img/bullet.png);">

    <li> <a href='spring://http://@start_script_mission:sandbox'>Sandbox</a> - just test the GUI and learn your own units</li>
    <li> <a href="spring://http://@start_script_mission:2v1">2v1</a> - play with AI against another AI</li>
    <li> <a href="spring://http://@start_script_mission:Very%20easy%20chickens">Very easy chickens</a> - defend yourself from hordes of chicken aliens</li>
     
  </ul>

  <h2>How to register a new account</h2><br />

  1.) First you'll see this form where you can enter a unique player name and password:<br />
      <img src="/img/tut/register.PNG" /><br /><br />

  2.) So, fill the textbox with your player name and password and click "register":<br />
      <img src="/img/tut/register2.PNG" /><br /><br />
  
  3.) Next, you have to agree to the "Terms of Use" before you can play with your account. Read the lines carefully and click "Accept":<br />
      <img src="/img/tut/register3.PNG" /><br /><br />

  4.) At last, check out the "Home" button and you will see your profile with some stats (e.g. your current level etc.):<br />
      <img src="/img/tut/register4.PNG" /><br /><br />
  
  5.) Now your account has been created successfully. Try some games, maybe multiplayer, and get some skill ;-)<br />
  
  Have fun!<br /><br />

  
  
  <h2>TroubleShooting</h2>

  <ul style="list-style-image:url(/img/bullet.png);">

    <li> Please make sure your graphic drivers are updated to latest! </li>
    <li> In case of game crashes disable shadows, lua shaders, water, pixel buffer and enable compressed textures. </li>
    <li> Make sure you read the <a href='/Wiki/FAQ'>FAQ</a>. </li>
    <li> Post a new thread in our <a href='/Forum'>forum</a>. </li>

  </ul>
  
</div>