<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UnlocksAdmin.aspx.cs" Inherits="ZeroKWeb.UnlocksAdmin" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
      <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="UnlockID" PageSize="40"
        DataSourceID="LinqDataSource1">
        <Columns>
        <asp:BoundField DataField="UnlockID" HeaderText="UnlockID" 
            SortExpression="UnlockID" />
        <asp:BoundField DataField="Code" HeaderText="Code" 
            SortExpression="Code" />
          <asp:BoundField DataField="Name" HeaderText="Name" 
            SortExpression="Name" />
          <asp:BoundField DataField="Description" HeaderText="Description" 
             SortExpression="Description" />
          <asp:BoundField DataField="NeededLevel" HeaderText="NeededLevel" 
             SortExpression="NeededLevel" />
          <asp:BoundField DataField="RequiredUnlockID" HeaderText="RequiredUnlockID" 
             SortExpression="RequiredUnlockID" />
          <asp:BoundField DataField="UnlockType" HeaderText="UnlockType" 
            SortExpression="UnlockType" />
            <asp:BoundField DataField="MorphLevel" HeaderText="MorphLevel" 
             SortExpression="MorphLevel" />
          <asp:BoundField DataField="LimitForChassis" HeaderText="LimitForChassis" 
             SortExpression="LimitForChassis" />
        </Columns>
      </asp:GridView>
      <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
        ContextTypeName="ZkData.ZkDataContext" EnableDelete="True" EnableInsert="True" 
        EnableUpdate="True" EntityTypeName="" 
        TableName="Unlocks">
      </asp:LinqDataSource>
    </div>

    <h3>Insert new</h3>
    Code: <asp:TextBox ID="tbCode" runat="server"></asp:TextBox><br />
    Name: <asp:TextBox ID="tbName" runat="server"></asp:TextBox><br />
    Description: <asp:TextBox ID="tbDescription" runat="server" Rows="4" Columns="40"></asp:TextBox><br />
    Needed level: <asp:TextBox ID="tbMinLevel" runat="server" Text="0"></asp:TextBox><br />
    Prerequisite (ID): <asp:TextBox ID="tbPreq" runat="server"></asp:TextBox><br />
    Unlock type: <asp:DropDownList ID="ddType" runat="server">
    </asp:DropDownList><br />
    Morph level (when module/weapon is available): <asp:TextBox ID="tbMorphLevel" runat="server"></asp:TextBox><br />
    For chassis (comma list): <asp:TextBox ID="tbChassisLimit" runat="server"></asp:TextBox><br />
    <asp:Button ID="btnAdd" runat="server" Text="Add new" onclick="btnAdd_Click" />
    </form>
</body>
</html>
