//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionEditor2.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissionData", Namespace="http://SpringMissionEditor/")]
    [System.SerializableAttribute()]
    public partial class MissionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MissionEditor2.ServiceReference.MissionInfo MissionInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MutatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MissionEditor2.ServiceReference.MissionInfo MissionInfo {
            get {
                return this.MissionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionInfoField, value) != true)) {
                    this.MissionInfoField = value;
                    this.RaisePropertyChanged("MissionInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Mutator {
            get {
                return this.MutatorField;
            }
            set {
                if ((object.ReferenceEquals(this.MutatorField, value) != true)) {
                    this.MutatorField = value;
                    this.RaisePropertyChanged("Mutator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissionInfo", Namespace="http://SpringMissionEditor/")]
    [System.SerializableAttribute()]
    public partial class MissionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        private int CommentCountField;
        
        private System.Nullable<System.DateTime> CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int DownloadCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        private System.Nullable<System.DateTime> LastCommentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapField;
        
        private int MissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private double RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoringMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopScoreLineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CommentCount {
            get {
                return this.CommentCountField;
            }
            set {
                if ((this.CommentCountField.Equals(value) != true)) {
                    this.CommentCountField = value;
                    this.RaisePropertyChanged("CommentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DownloadCount {
            get {
                return this.DownloadCountField;
            }
            set {
                if ((this.DownloadCountField.Equals(value) != true)) {
                    this.DownloadCountField = value;
                    this.RaisePropertyChanged("DownloadCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> LastCommentTime {
            get {
                return this.LastCommentTimeField;
            }
            set {
                if ((this.LastCommentTimeField.Equals(value) != true)) {
                    this.LastCommentTimeField = value;
                    this.RaisePropertyChanged("LastCommentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MissionID {
            get {
                return this.MissionIDField;
            }
            set {
                if ((this.MissionIDField.Equals(value) != true)) {
                    this.MissionIDField = value;
                    this.RaisePropertyChanged("MissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mod {
            get {
                return this.ModField;
            }
            set {
                if ((object.ReferenceEquals(this.ModField, value) != true)) {
                    this.ModField = value;
                    this.RaisePropertyChanged("Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> ModifiedTime {
            get {
                return this.ModifiedTimeField;
            }
            set {
                if ((this.ModifiedTimeField.Equals(value) != true)) {
                    this.ModifiedTimeField = value;
                    this.RaisePropertyChanged("ModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ScoringMethod {
            get {
                return this.ScoringMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoringMethodField, value) != true)) {
                    this.ScoringMethodField = value;
                    this.RaisePropertyChanged("ScoringMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TopScoreLine {
            get {
                return this.TopScoreLineField;
            }
            set {
                if ((object.ReferenceEquals(this.TopScoreLineField, value) != true)) {
                    this.TopScoreLineField = value;
                    this.RaisePropertyChanged("TopScoreLine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreEntry", Namespace="http://SpringMissionEditor/")]
    [System.SerializableAttribute()]
    public partial class ScoreEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        private int ScoreField;
        
        private int TimeSecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TimeSeconds {
            get {
                return this.TimeSecondsField;
            }
            set {
                if ((this.TimeSecondsField.Equals(value) != true)) {
                    this.TimeSecondsField = value;
                    this.RaisePropertyChanged("TimeSeconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentInfo", Namespace="http://SpringMissionEditor/")]
    [System.SerializableAttribute()]
    public partial class CommentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SpringMissionEditor/", ConfigurationName="ServiceReference.EditorServiceSoap")]
    public interface EditorServiceSoap {
        
        // CODEGEN: Generating message contract since element name nick from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/AddComment", ReplyAction="*")]
        MissionEditor2.ServiceReference.AddCommentResponse AddComment(MissionEditor2.ServiceReference.AddCommentRequest request);
        
        // CODEGEN: Generating message contract since element name author from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/DeleteMission", ReplyAction="*")]
        MissionEditor2.ServiceReference.DeleteMissionResponse DeleteMission(MissionEditor2.ServiceReference.DeleteMissionRequest request);
        
        // CODEGEN: Generating message contract since element name missionName from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/GetMission", ReplyAction="*")]
        MissionEditor2.ServiceReference.GetMissionResponse GetMission(MissionEditor2.ServiceReference.GetMissionRequest request);
        
        // CODEGEN: Generating message contract since element name GetMissionByIDResult from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/GetMissionByID", ReplyAction="*")]
        MissionEditor2.ServiceReference.GetMissionByIDResponse GetMissionByID(MissionEditor2.ServiceReference.GetMissionByIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetScoresResult from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/GetScores", ReplyAction="*")]
        MissionEditor2.ServiceReference.GetScoresResponse GetScores(MissionEditor2.ServiceReference.GetScoresRequest request);
        
        // CODEGEN: Generating message contract since element name ListCommentsResult from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/ListComments", ReplyAction="*")]
        MissionEditor2.ServiceReference.ListCommentsResponse ListComments(MissionEditor2.ServiceReference.ListCommentsRequest request);
        
        // CODEGEN: Generating message contract since element name ListMissionInfosResult from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/ListMissionInfos", ReplyAction="*")]
        MissionEditor2.ServiceReference.ListMissionInfosResponse ListMissionInfos(MissionEditor2.ServiceReference.ListMissionInfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/Rate", ReplyAction="*")]
        void Rate(int missionID, double rating);
        
        // CODEGEN: Generating message contract since element name mission from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/SendMission", ReplyAction="*")]
        MissionEditor2.ServiceReference.SendMissionResponse SendMission(MissionEditor2.ServiceReference.SendMissionRequest request);
        
        // CODEGEN: Generating message contract since element name missionName from namespace http://SpringMissionEditor/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SpringMissionEditor/SubmitScore", ReplyAction="*")]
        MissionEditor2.ServiceReference.SubmitScoreResponse SubmitScore(MissionEditor2.ServiceReference.SubmitScoreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddComment", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.AddCommentRequestBody Body;
        
        public AddCommentRequest() {
        }
        
        public AddCommentRequest(MissionEditor2.ServiceReference.AddCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class AddCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int missionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        public AddCommentRequestBody() {
        }
        
        public AddCommentRequestBody(string nick, int missionID, string text) {
            this.nick = nick;
            this.missionID = missionID;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCommentResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.AddCommentResponseBody Body;
        
        public AddCommentResponse() {
        }
        
        public AddCommentResponse(MissionEditor2.ServiceReference.AddCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCommentResponseBody {
        
        public AddCommentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMission", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.DeleteMissionRequestBody Body;
        
        public DeleteMissionRequest() {
        }
        
        public DeleteMissionRequest(MissionEditor2.ServiceReference.DeleteMissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class DeleteMissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int missionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public DeleteMissionRequestBody() {
        }
        
        public DeleteMissionRequestBody(int missionID, string author, string password) {
            this.missionID = missionID;
            this.author = author;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMissionResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.DeleteMissionResponseBody Body;
        
        public DeleteMissionResponse() {
        }
        
        public DeleteMissionResponse(MissionEditor2.ServiceReference.DeleteMissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteMissionResponseBody {
        
        public DeleteMissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMission", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetMissionRequestBody Body;
        
        public GetMissionRequest() {
        }
        
        public GetMissionRequest(MissionEditor2.ServiceReference.GetMissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetMissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string missionName;
        
        public GetMissionRequestBody() {
        }
        
        public GetMissionRequestBody(string missionName) {
            this.missionName = missionName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMissionResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetMissionResponseBody Body;
        
        public GetMissionResponse() {
        }
        
        public GetMissionResponse(MissionEditor2.ServiceReference.GetMissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetMissionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.MissionData GetMissionResult;
        
        public GetMissionResponseBody() {
        }
        
        public GetMissionResponseBody(MissionEditor2.ServiceReference.MissionData GetMissionResult) {
            this.GetMissionResult = GetMissionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMissionByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMissionByID", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetMissionByIDRequestBody Body;
        
        public GetMissionByIDRequest() {
        }
        
        public GetMissionByIDRequest(MissionEditor2.ServiceReference.GetMissionByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetMissionByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int missionID;
        
        public GetMissionByIDRequestBody() {
        }
        
        public GetMissionByIDRequestBody(int missionID) {
            this.missionID = missionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMissionByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMissionByIDResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetMissionByIDResponseBody Body;
        
        public GetMissionByIDResponse() {
        }
        
        public GetMissionByIDResponse(MissionEditor2.ServiceReference.GetMissionByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetMissionByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.MissionData GetMissionByIDResult;
        
        public GetMissionByIDResponseBody() {
        }
        
        public GetMissionByIDResponseBody(MissionEditor2.ServiceReference.MissionData GetMissionByIDResult) {
            this.GetMissionByIDResult = GetMissionByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetScoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetScores", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetScoresRequestBody Body;
        
        public GetScoresRequest() {
        }
        
        public GetScoresRequest(MissionEditor2.ServiceReference.GetScoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetScoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int missionID;
        
        public GetScoresRequestBody() {
        }
        
        public GetScoresRequestBody(int missionID) {
            this.missionID = missionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetScoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetScoresResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.GetScoresResponseBody Body;
        
        public GetScoresResponse() {
        }
        
        public GetScoresResponse(MissionEditor2.ServiceReference.GetScoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class GetScoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.ScoreEntry[] GetScoresResult;
        
        public GetScoresResponseBody() {
        }
        
        public GetScoresResponseBody(MissionEditor2.ServiceReference.ScoreEntry[] GetScoresResult) {
            this.GetScoresResult = GetScoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListComments", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.ListCommentsRequestBody Body;
        
        public ListCommentsRequest() {
        }
        
        public ListCommentsRequest(MissionEditor2.ServiceReference.ListCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class ListCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int missionID;
        
        public ListCommentsRequestBody() {
        }
        
        public ListCommentsRequestBody(int missionID) {
            this.missionID = missionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListCommentsResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.ListCommentsResponseBody Body;
        
        public ListCommentsResponse() {
        }
        
        public ListCommentsResponse(MissionEditor2.ServiceReference.ListCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class ListCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.CommentInfo[] ListCommentsResult;
        
        public ListCommentsResponseBody() {
        }
        
        public ListCommentsResponseBody(MissionEditor2.ServiceReference.CommentInfo[] ListCommentsResult) {
            this.ListCommentsResult = ListCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListMissionInfosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListMissionInfos", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.ListMissionInfosRequestBody Body;
        
        public ListMissionInfosRequest() {
        }
        
        public ListMissionInfosRequest(MissionEditor2.ServiceReference.ListMissionInfosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListMissionInfosRequestBody {
        
        public ListMissionInfosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListMissionInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListMissionInfosResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.ListMissionInfosResponseBody Body;
        
        public ListMissionInfosResponse() {
        }
        
        public ListMissionInfosResponse(MissionEditor2.ServiceReference.ListMissionInfosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class ListMissionInfosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.MissionInfo[] ListMissionInfosResult;
        
        public ListMissionInfosResponseBody() {
        }
        
        public ListMissionInfosResponseBody(MissionEditor2.ServiceReference.MissionInfo[] ListMissionInfosResult) {
            this.ListMissionInfosResult = ListMissionInfosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMission", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.SendMissionRequestBody Body;
        
        public SendMissionRequest() {
        }
        
        public SendMissionRequest(MissionEditor2.ServiceReference.SendMissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class SendMissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MissionEditor2.ServiceReference.MissionData mission;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public SendMissionRequestBody() {
        }
        
        public SendMissionRequestBody(MissionEditor2.ServiceReference.MissionData mission, string author, string password) {
            this.mission = mission;
            this.author = author;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMissionResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.SendMissionResponseBody Body;
        
        public SendMissionResponse() {
        }
        
        public SendMissionResponse(MissionEditor2.ServiceReference.SendMissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMissionResponseBody {
        
        public SendMissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitScore", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.SubmitScoreRequestBody Body;
        
        public SubmitScoreRequest() {
        }
        
        public SubmitScoreRequest(MissionEditor2.ServiceReference.SubmitScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SpringMissionEditor/")]
    public partial class SubmitScoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string missionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string playerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int score;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int timeSeconds;
        
        public SubmitScoreRequestBody() {
        }
        
        public SubmitScoreRequestBody(string missionName, string playerName, int score, int timeSeconds) {
            this.missionName = missionName;
            this.playerName = playerName;
            this.score = score;
            this.timeSeconds = timeSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitScoreResponse", Namespace="http://SpringMissionEditor/", Order=0)]
        public MissionEditor2.ServiceReference.SubmitScoreResponseBody Body;
        
        public SubmitScoreResponse() {
        }
        
        public SubmitScoreResponse(MissionEditor2.ServiceReference.SubmitScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SubmitScoreResponseBody {
        
        public SubmitScoreResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EditorServiceSoapChannel : MissionEditor2.ServiceReference.EditorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditorServiceSoapClient : System.ServiceModel.ClientBase<MissionEditor2.ServiceReference.EditorServiceSoap>, MissionEditor2.ServiceReference.EditorServiceSoap {
        
        public EditorServiceSoapClient() {
        }
        
        public EditorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EditorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.AddCommentResponse MissionEditor2.ServiceReference.EditorServiceSoap.AddComment(MissionEditor2.ServiceReference.AddCommentRequest request) {
            return base.Channel.AddComment(request);
        }
        
        public void AddComment(string nick, int missionID, string text) {
            MissionEditor2.ServiceReference.AddCommentRequest inValue = new MissionEditor2.ServiceReference.AddCommentRequest();
            inValue.Body = new MissionEditor2.ServiceReference.AddCommentRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.missionID = missionID;
            inValue.Body.text = text;
            MissionEditor2.ServiceReference.AddCommentResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).AddComment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.DeleteMissionResponse MissionEditor2.ServiceReference.EditorServiceSoap.DeleteMission(MissionEditor2.ServiceReference.DeleteMissionRequest request) {
            return base.Channel.DeleteMission(request);
        }
        
        public void DeleteMission(int missionID, string author, string password) {
            MissionEditor2.ServiceReference.DeleteMissionRequest inValue = new MissionEditor2.ServiceReference.DeleteMissionRequest();
            inValue.Body = new MissionEditor2.ServiceReference.DeleteMissionRequestBody();
            inValue.Body.missionID = missionID;
            inValue.Body.author = author;
            inValue.Body.password = password;
            MissionEditor2.ServiceReference.DeleteMissionResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).DeleteMission(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.GetMissionResponse MissionEditor2.ServiceReference.EditorServiceSoap.GetMission(MissionEditor2.ServiceReference.GetMissionRequest request) {
            return base.Channel.GetMission(request);
        }
        
        public MissionEditor2.ServiceReference.MissionData GetMission(string missionName) {
            MissionEditor2.ServiceReference.GetMissionRequest inValue = new MissionEditor2.ServiceReference.GetMissionRequest();
            inValue.Body = new MissionEditor2.ServiceReference.GetMissionRequestBody();
            inValue.Body.missionName = missionName;
            MissionEditor2.ServiceReference.GetMissionResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).GetMission(inValue);
            return retVal.Body.GetMissionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.GetMissionByIDResponse MissionEditor2.ServiceReference.EditorServiceSoap.GetMissionByID(MissionEditor2.ServiceReference.GetMissionByIDRequest request) {
            return base.Channel.GetMissionByID(request);
        }
        
        public MissionEditor2.ServiceReference.MissionData GetMissionByID(int missionID) {
            MissionEditor2.ServiceReference.GetMissionByIDRequest inValue = new MissionEditor2.ServiceReference.GetMissionByIDRequest();
            inValue.Body = new MissionEditor2.ServiceReference.GetMissionByIDRequestBody();
            inValue.Body.missionID = missionID;
            MissionEditor2.ServiceReference.GetMissionByIDResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).GetMissionByID(inValue);
            return retVal.Body.GetMissionByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.GetScoresResponse MissionEditor2.ServiceReference.EditorServiceSoap.GetScores(MissionEditor2.ServiceReference.GetScoresRequest request) {
            return base.Channel.GetScores(request);
        }
        
        public MissionEditor2.ServiceReference.ScoreEntry[] GetScores(int missionID) {
            MissionEditor2.ServiceReference.GetScoresRequest inValue = new MissionEditor2.ServiceReference.GetScoresRequest();
            inValue.Body = new MissionEditor2.ServiceReference.GetScoresRequestBody();
            inValue.Body.missionID = missionID;
            MissionEditor2.ServiceReference.GetScoresResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).GetScores(inValue);
            return retVal.Body.GetScoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.ListCommentsResponse MissionEditor2.ServiceReference.EditorServiceSoap.ListComments(MissionEditor2.ServiceReference.ListCommentsRequest request) {
            return base.Channel.ListComments(request);
        }
        
        public MissionEditor2.ServiceReference.CommentInfo[] ListComments(int missionID) {
            MissionEditor2.ServiceReference.ListCommentsRequest inValue = new MissionEditor2.ServiceReference.ListCommentsRequest();
            inValue.Body = new MissionEditor2.ServiceReference.ListCommentsRequestBody();
            inValue.Body.missionID = missionID;
            MissionEditor2.ServiceReference.ListCommentsResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).ListComments(inValue);
            return retVal.Body.ListCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.ListMissionInfosResponse MissionEditor2.ServiceReference.EditorServiceSoap.ListMissionInfos(MissionEditor2.ServiceReference.ListMissionInfosRequest request) {
            return base.Channel.ListMissionInfos(request);
        }
        
        public MissionEditor2.ServiceReference.MissionInfo[] ListMissionInfos() {
            MissionEditor2.ServiceReference.ListMissionInfosRequest inValue = new MissionEditor2.ServiceReference.ListMissionInfosRequest();
            inValue.Body = new MissionEditor2.ServiceReference.ListMissionInfosRequestBody();
            MissionEditor2.ServiceReference.ListMissionInfosResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).ListMissionInfos(inValue);
            return retVal.Body.ListMissionInfosResult;
        }
        
        public void Rate(int missionID, double rating) {
            base.Channel.Rate(missionID, rating);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.SendMissionResponse MissionEditor2.ServiceReference.EditorServiceSoap.SendMission(MissionEditor2.ServiceReference.SendMissionRequest request) {
            return base.Channel.SendMission(request);
        }
        
        public void SendMission(MissionEditor2.ServiceReference.MissionData mission, string author, string password) {
            MissionEditor2.ServiceReference.SendMissionRequest inValue = new MissionEditor2.ServiceReference.SendMissionRequest();
            inValue.Body = new MissionEditor2.ServiceReference.SendMissionRequestBody();
            inValue.Body.mission = mission;
            inValue.Body.author = author;
            inValue.Body.password = password;
            MissionEditor2.ServiceReference.SendMissionResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).SendMission(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MissionEditor2.ServiceReference.SubmitScoreResponse MissionEditor2.ServiceReference.EditorServiceSoap.SubmitScore(MissionEditor2.ServiceReference.SubmitScoreRequest request) {
            return base.Channel.SubmitScore(request);
        }
        
        public void SubmitScore(string missionName, string playerName, int score, int timeSeconds) {
            MissionEditor2.ServiceReference.SubmitScoreRequest inValue = new MissionEditor2.ServiceReference.SubmitScoreRequest();
            inValue.Body = new MissionEditor2.ServiceReference.SubmitScoreRequestBody();
            inValue.Body.missionName = missionName;
            inValue.Body.playerName = playerName;
            inValue.Body.score = score;
            inValue.Body.timeSeconds = timeSeconds;
            MissionEditor2.ServiceReference.SubmitScoreResponse retVal = ((MissionEditor2.ServiceReference.EditorServiceSoap)(this)).SubmitScore(inValue);
        }
    }
}
