<div id="news" class="border">
	<h1>New Website!</h1>
	<p>The new website for Zero-K players is finally here!</p>
	<p>We're really excited to present this brand-new website for this awesome game. I hope the experienced players enjoy the new layout and look. There is more to come! The main page will be a portal to all of your Zero-K needs; very soon we will start up a "Unit of the Day" which helpfully describes a unit from a large and various collection in the game. Those curious of the new and ongoing development will have easy access to the revision logs, as well as an up to date list of our top players.</p>
	<p>Since Zero-K is a community project, we would gladly welcome any help or feedback. If you can't model, or can't code, there are still ways for you to help! The wiki can be filled with helpful information, guides can be written to help newcomers, text can be translated into your native language.</p>
</div>