	<meta name="description" content="Zero-K is a FREE, multiplatform, open-source RTS game, which aims to be a dynamic, action-packed, hassle-free game, full of clever strategies and constantly moving combat which usually lasts on average 20-30 minutes." />
	<meta name="keywords" content="Zero K, zero-k, game, rts, Real Time Strategy, awesome, robot, mech" />
	<link rel="stylesheet" href="style.css" type="text/css"/>
	<link rel="icon" href="img/favicon.png" />
	<script type="text/javascript" language="JavaScript" src="scripts/base.js"></script>
