<div id="features" class="border left part">
	<p>Zero-K is a FREE, multiplatform, open-source RTS game, which aims to be a dynamic, action-packed, hassle-free game, full of clever strategies and constantly moving combat which usually lasts on average 20-30 minutes.</p>
	<p>Some of the more prominent features:</p>
	<ul class="points">
		<li><b>Epic Scale</b> from tiny fleas to huge mechs and gigantic superweapons that wreak havoc - hundreds or thousands of units on the battlefield, all easily viewable with a fully zoomable camera.</li>
		<li><b>Realistic Physics</b> mean each shot is physically simulated realtime - you can actually evade bullets if you micro-manage your units! Hills and terrain affect line of sight and radar coverage, explosions create deformations, etc...</li>
		<!-- <li><b>Natural Balance</b> allows units to depend on their natural characteristics and the benefits of the simulated environment, not contrived special damages to determine their effectiveness.</li> -->
		<li><b>Terraforming</b> - change the terrain: walls, ditches, ramps and more, to provide yourself with an extra tactical advantage.</li>
		<li><b>Unique Abilities</b> make sure units are fun to use! From jump-jets, gravity turrets, mobile shields, burning napalm, air drops, unit morphs - we've got it all and more! You can even control your units directly in First Person Mode!<!--when the wiki/guides get put up these could use some links--></li>
		<li><b>Streamlined Economy</b> - since resources are unlimited, your economy expands gracefully as the game progresses and without boring economic micro-management, allowing you to focus on more important tasks at hand.</li>
		<li><b>Planet Wars</b> lets you take control of your own planet and fight for survival in an ongoing online campaign! <a href="http://planet-wars.eu/">Grab your planet today!</a></li>
	</ul>
	<p>There are a lot more amazing things to tell, but listing them out is boring, try them out by visiting our <a href="download.php">downloads</a> page.</p>
	<p>Zero-K is made by players, for players. All the game developers are active participants in epic wars between robots (not to mention <a href="">chickens</a>). Balance and fun is assured.</p>
</div><!close content>
