<div id="poll" class="border">
	<h2><a>Poll</a></h1>
	What is your favorite kind of cake?
	<form action="poll.php">
	<ul class="poll">
		<li><input type="radio" name="option" value="Vanilla" checked /> Vanilla </li>
		<li><input type="radio" name="option" value="Chocolate" /> Chocolate </li>
		<li><input type="radio" name="option" value="Strawberry" /> Strawberry </li>
		<li><input type="radio" name="option" value="Lemon" /> Lemon </li>
		<li><input type="radio" name="option" value="Wrong" /> The Cake is a Lie </li>
	</ul>
	<center><input type="submit" value="vote" class="button border" /></center>
	</form>
</div><!close poll>