// <auto-generated />
namespace PlasmaShared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FixCampaignLinkKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCampaignLinkKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201501031252225_FixCampaignLinkKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
