//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetWars.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanetWars.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editclear {
            get {
                object obj = ResourceManager.GetObject("editclear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap galaxy {
            get {
                object obj = ResourceManager.GetObject("galaxy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_magnify {
            get {
                object obj = ResourceManager.GetObject("map_magnify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adalmo
        ///Adamoyano
        ///Adariarak
        ///Adasut
        ///Adiman
        ///Adrincir
        ///Aeithe
        ///Aerakaneh
        ///Aerigura
        ///Aethe
        ///Agolaid
        ///Agon
        ///Agru
        ///Aguin
        ///Agura
        ///Agurem
        ///Agus
        ///Ahmromir
        ///Ailkira
        ///Ailyrazia
        ///Ainivesh
        ///Aintirca
        ///Aireal
        ///Airein
        ///Airota
        ///Akestlir
        ///Akikkary
        ///Akikua
        ///Alabethe
        ///Alaec
        ///Alairivon
        ///Alat
        ///Alazierno
        ///Albanja
        ///Alhaydell
        ///Alhaz
        ///Alior
        ///Allo
        ///Amangru
        ///Anderashi
        ///Angros
        ///Angyr
        ///Anios
        ///Anirreera
        ///Ardard
        ///Arderibus
        ///Ardstrava
        ///Arelitia
        ///Arewzell
        ///Areyash
        ///Argalmo
        ///Arigin
        ///Arimonvi
        ///Aris
        ///Arkaslac
        ///Arkodanti
        ///Arkome
        ///Arlantan
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 Tauri
        ///17 Tauri
        ///19 Tauri
        ///20 Tauri
        ///21 Tauri
        ///22 Tauri
        ///23 Tauri
        ///27 Tauri
        ///28 Tauri - see Pleiades
        ///31 Lyncis
        ///38 Bo�tis
        ///41 Arietis
        ///46 Leo Minoris
        ///46 Leonis Minoris
        ///53 Eridani
        ///80 Ursae Majoris
        ///Acamar
        ///Achernar
        ///Achird
        ///Acrab
        ///Acrux
        ///Acubens
        ///Adhafera
        ///Adhara
        ///Ain
        ///Al Fawaris
        ///Al Giedi
        ///Al Kalb al Rai
        ///Al Kaphrah
        ///Al Kurud
        ///Al Minliar al Asad
        ///Al Nair
        ///Al Niyat
        ///Al Thalimain
        ///Aladfar
        ///Alamak
        ///Alaraph
        ///Alathfar
        ///Albaldah
        ///Albali
        ///Albireo
        ///Alchiba
        ///Alcor
        ///Alcor 
        ///Alcyone
        ///Alcyone 
        ///Aldebaran
        ///Alderam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stars {
            get {
                return ResourceManager.GetString("stars", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap world {
            get {
                object obj = ResourceManager.GetObject("world", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
